### ISSUE TITLE
Segmentation fault in process_keystroke

### ISSUE THREAD

**Issue by eigengrau** [emgram769/lighthouse#12]
When the following key sequence is input, lighthouse will segfault:

```
KeyPress event, serial 33, synthetic NO, window 0x2e00001,
    root 0x2bb, subw 0x0, time 7040730, (271,417), root:(1232,418),
    state 0x0, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 33, synthetic NO, window 0x2e00001,
    root 0x2bb, subw 0x0, time 7040971, (271,417), root:(1232,418),
    state 0x1, keycode 12 (keysym 0x1002113, U2113), same_screen YES,
    XLookupString gives 3 bytes: (e2 84 93) "ℓ"
    XmbLookupString gives 3 bytes: (e2 84 93) "ℓ"
    XFilterEvent returns: False

KeyRelease event, serial 33, synthetic NO, window 0x2e00001,
    root 0x2bb, subw 0x0, time 7041363, (271,417), root:(1232,418),
    state 0x1, keycode 12 (keysym 0x1002113, U2113), same_screen YES,
    XLookupString gives 3 bytes: (e2 84 93) "ℓ"
    XFilterEvent returns: False

KeyRelease event, serial 33, synthetic NO, window 0x2e00001,
    root 0x2bb, subw 0x0, time 7041547, (271,417), root:(1232,418),
    state 0x1, keycode 50 (keysym 0xffe5, Caps_Lock), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

Backtrace here:

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000404758 in process_key_stroke (query_buffer=0x7fffffffd990 "", 
    query_index=0x7fffffffd98c, query_cursor_index=0x7fffffffd988, key=16785683, 
    connection=0x610430, cairo_context=0x622780, cairo_surface=0x622360, to_write=0x6100d0)
    at src/lighthouse.c:654
654       if (isprint(key) && *query_index < MAX_QUERY) {
(gdb) bt
#0  0x0000000000404758 in process_key_stroke (query_buffer=0x7fffffffd990 "", 
    query_index=0x7fffffffd98c, query_cursor_index=0x7fffffffd988, key=16785683, 
    connection=0x610430, cairo_context=0x622780, cairo_surface=0x622360, to_write=0x6100d0)
    at src/lighthouse.c:654
#1  0x0000000000405d9c in main (argc=1, argv=0x7fffffffdfb8) at src/lighthouse.c:1151
```

**Comment by kolibry** [comment]
Hi,
Seems nice, I got an issue though.

I have a laptop connected to an external monitor. I can get lighthouse to run if I use my laptop's screen, although in my external screen I get : 

`Unable to connect to randr crtc
zsh: segmentation fault (core dumped)  lighthouse`

**Comment by eigengrau** [comment]
On 5994050, I’m no longer seeing the segfault, but no characters appear in the echo box, unless the character is ASCII. Since the same thing happens for some non-shifted characters, I’m closing this for another issue.

**Comment by eigengrau** [comment]
#17
